version: '3.7'
services:
  duiztdb:
    image: postgres:latest
    container_name: duiztdb
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=duiztdb
    expose: 
      - 5432
    ports: 
      - "5432:5432"
    networks:
      - duizt_net 
networks:
  duizt_net:
    driver: bridge