// Code generated by entc, DO NOT EDIT.

package i18n

const (
	// Label holds the string label denoting the i18n type in the database.
	Label = "i18n"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"

	// EdgeAnswerLangs holds the string denoting the answer_langs edge name in mutations.
	EdgeAnswerLangs = "answer_langs"
	// EdgeQuestionLangs holds the string denoting the question_langs edge name in mutations.
	EdgeQuestionLangs = "question_langs"
	// EdgeQuizLangs holds the string denoting the quiz_langs edge name in mutations.
	EdgeQuizLangs = "quiz_langs"

	// Table holds the table name of the i18n in the database.
	Table = "i18ns"
	// AnswerLangsTable is the table the holds the answer_langs relation/edge.
	AnswerLangsTable = "answer_langs"
	// AnswerLangsInverseTable is the table name for the AnswerLangs entity.
	// It exists in this package in order to avoid circular dependency with the "answerlangs" package.
	AnswerLangsInverseTable = "answer_langs"
	// AnswerLangsColumn is the table column denoting the answer_langs relation/edge.
	AnswerLangsColumn = "i18n_answer_langs"
	// QuestionLangsTable is the table the holds the question_langs relation/edge.
	QuestionLangsTable = "question_langs"
	// QuestionLangsInverseTable is the table name for the QuestionLangs entity.
	// It exists in this package in order to avoid circular dependency with the "questionlangs" package.
	QuestionLangsInverseTable = "question_langs"
	// QuestionLangsColumn is the table column denoting the question_langs relation/edge.
	QuestionLangsColumn = "i18n_question_langs"
	// QuizLangsTable is the table the holds the quiz_langs relation/edge.
	QuizLangsTable = "quiz_langs"
	// QuizLangsInverseTable is the table name for the QuizLangs entity.
	// It exists in this package in order to avoid circular dependency with the "quizlangs" package.
	QuizLangsInverseTable = "quiz_langs"
	// QuizLangsColumn is the table column denoting the quiz_langs relation/edge.
	QuizLangsColumn = "i18n_quiz_langs"
)

// Columns holds all SQL columns for i18n fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldLanguage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
