// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/vmkevv/duiztapi/ent/answer"
	"github.com/vmkevv/duiztapi/ent/question"
)

// Answer is the model entity for the Answer schema.
type Answer struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswerQuery when eager-loading is set.
	Edges            AnswerEdges `json:"edges"`
	question_answers *int
}

// AnswerEdges holds the relations/edges for other nodes in the graph.
type AnswerEdges struct {
	// Langs holds the value of the langs edge.
	Langs []*AnswerLangs
	// Responses holds the value of the responses edge.
	Responses []*Response
	// Question holds the value of the question edge.
	Question *Question
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// LangsOrErr returns the Langs value or an error if the edge
// was not loaded in eager-loading.
func (e AnswerEdges) LangsOrErr() ([]*AnswerLangs, error) {
	if e.loadedTypes[0] {
		return e.Langs, nil
	}
	return nil, &NotLoadedError{edge: "langs"}
}

// ResponsesOrErr returns the Responses value or an error if the edge
// was not loaded in eager-loading.
func (e AnswerEdges) ResponsesOrErr() ([]*Response, error) {
	if e.loadedTypes[1] {
		return e.Responses, nil
	}
	return nil, &NotLoadedError{edge: "responses"}
}

// QuestionOrErr returns the Question value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnswerEdges) QuestionOrErr() (*Question, error) {
	if e.loadedTypes[2] {
		if e.Question == nil {
			// The edge question was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: question.Label}
		}
		return e.Question, nil
	}
	return nil, &NotLoadedError{edge: "question"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Answer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case answer.FieldID:
			values[i] = &sql.NullInt64{}
		case answer.ForeignKeys[0]: // question_answers
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type Answer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Answer fields.
func (a *Answer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case answer.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field question_answers", value)
			} else if value.Valid {
				a.question_answers = new(int)
				*a.question_answers = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryLangs queries the "langs" edge of the Answer entity.
func (a *Answer) QueryLangs() *AnswerLangsQuery {
	return (&AnswerClient{config: a.config}).QueryLangs(a)
}

// QueryResponses queries the "responses" edge of the Answer entity.
func (a *Answer) QueryResponses() *ResponseQuery {
	return (&AnswerClient{config: a.config}).QueryResponses(a)
}

// QueryQuestion queries the "question" edge of the Answer entity.
func (a *Answer) QueryQuestion() *QuestionQuery {
	return (&AnswerClient{config: a.config}).QueryQuestion(a)
}

// Update returns a builder for updating this Answer.
// Note that you need to call Answer.Unwrap() before calling this method if this Answer
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Answer) Update() *AnswerUpdateOne {
	return (&AnswerClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Answer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Answer) Unwrap() *Answer {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Answer is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Answer) String() string {
	var builder strings.Builder
	builder.WriteString("Answer(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Answers is a parsable slice of Answer.
type Answers []*Answer

func (a Answers) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
