// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vmkevv/duiztapi/ent/answer"
	"github.com/vmkevv/duiztapi/ent/answerlangs"
	"github.com/vmkevv/duiztapi/ent/i18n"
)

// AnswerLangsCreate is the builder for creating a AnswerLangs entity.
type AnswerLangsCreate struct {
	config
	mutation *AnswerLangsMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (alc *AnswerLangsCreate) SetText(s string) *AnswerLangsCreate {
	alc.mutation.SetText(s)
	return alc
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (alc *AnswerLangsCreate) SetAnswerID(id int) *AnswerLangsCreate {
	alc.mutation.SetAnswerID(id)
	return alc
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (alc *AnswerLangsCreate) SetNillableAnswerID(id *int) *AnswerLangsCreate {
	if id != nil {
		alc = alc.SetAnswerID(*id)
	}
	return alc
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (alc *AnswerLangsCreate) SetAnswer(a *Answer) *AnswerLangsCreate {
	return alc.SetAnswerID(a.ID)
}

// SetI18nID sets the "i18n" edge to the I18n entity by ID.
func (alc *AnswerLangsCreate) SetI18nID(id int) *AnswerLangsCreate {
	alc.mutation.SetI18nID(id)
	return alc
}

// SetNillableI18nID sets the "i18n" edge to the I18n entity by ID if the given value is not nil.
func (alc *AnswerLangsCreate) SetNillableI18nID(id *int) *AnswerLangsCreate {
	if id != nil {
		alc = alc.SetI18nID(*id)
	}
	return alc
}

// SetI18n sets the "i18n" edge to the I18n entity.
func (alc *AnswerLangsCreate) SetI18n(i *I18n) *AnswerLangsCreate {
	return alc.SetI18nID(i.ID)
}

// Mutation returns the AnswerLangsMutation object of the builder.
func (alc *AnswerLangsCreate) Mutation() *AnswerLangsMutation {
	return alc.mutation
}

// Save creates the AnswerLangs in the database.
func (alc *AnswerLangsCreate) Save(ctx context.Context) (*AnswerLangs, error) {
	var (
		err  error
		node *AnswerLangs
	)
	if len(alc.hooks) == 0 {
		if err = alc.check(); err != nil {
			return nil, err
		}
		node, err = alc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AnswerLangsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = alc.check(); err != nil {
				return nil, err
			}
			alc.mutation = mutation
			node, err = alc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(alc.hooks) - 1; i >= 0; i-- {
			mut = alc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, alc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (alc *AnswerLangsCreate) SaveX(ctx context.Context) *AnswerLangs {
	v, err := alc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (alc *AnswerLangsCreate) check() error {
	if _, ok := alc.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New("ent: missing required field \"text\"")}
	}
	return nil
}

func (alc *AnswerLangsCreate) sqlSave(ctx context.Context) (*AnswerLangs, error) {
	_node, _spec := alc.createSpec()
	if err := sqlgraph.CreateNode(ctx, alc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (alc *AnswerLangsCreate) createSpec() (*AnswerLangs, *sqlgraph.CreateSpec) {
	var (
		_node = &AnswerLangs{config: alc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: answerlangs.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: answerlangs.FieldID,
			},
		}
	)
	if value, ok := alc.mutation.Text(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: answerlangs.FieldText,
		})
		_node.Text = value
	}
	if nodes := alc.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answerlangs.AnswerTable,
			Columns: []string{answerlangs.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: answer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := alc.mutation.I18nIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answerlangs.I18nTable,
			Columns: []string{answerlangs.I18nColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: i18n.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnswerLangsCreateBulk is the builder for creating many AnswerLangs entities in bulk.
type AnswerLangsCreateBulk struct {
	config
	builders []*AnswerLangsCreate
}

// Save creates the AnswerLangs entities in the database.
func (alcb *AnswerLangsCreateBulk) Save(ctx context.Context) ([]*AnswerLangs, error) {
	specs := make([]*sqlgraph.CreateSpec, len(alcb.builders))
	nodes := make([]*AnswerLangs, len(alcb.builders))
	mutators := make([]Mutator, len(alcb.builders))
	for i := range alcb.builders {
		func(i int, root context.Context) {
			builder := alcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswerLangsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, alcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, alcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, alcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (alcb *AnswerLangsCreateBulk) SaveX(ctx context.Context) []*AnswerLangs {
	v, err := alcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
