// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vmkevv/duiztapi/ent/predicate"
	"github.com/vmkevv/duiztapi/ent/quizlangs"
)

// QuizLangsDelete is the builder for deleting a QuizLangs entity.
type QuizLangsDelete struct {
	config
	hooks    []Hook
	mutation *QuizLangsMutation
}

// Where adds a new predicate to the QuizLangsDelete builder.
func (qld *QuizLangsDelete) Where(ps ...predicate.QuizLangs) *QuizLangsDelete {
	qld.mutation.predicates = append(qld.mutation.predicates, ps...)
	return qld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qld *QuizLangsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qld.hooks) == 0 {
		affected, err = qld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuizLangsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qld.mutation = mutation
			affected, err = qld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qld.hooks) - 1; i >= 0; i-- {
			mut = qld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qld *QuizLangsDelete) ExecX(ctx context.Context) int {
	n, err := qld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qld *QuizLangsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: quizlangs.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: quizlangs.FieldID,
			},
		},
	}
	if ps := qld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, qld.driver, _spec)
}

// QuizLangsDeleteOne is the builder for deleting a single QuizLangs entity.
type QuizLangsDeleteOne struct {
	qld *QuizLangsDelete
}

// Exec executes the deletion query.
func (qldo *QuizLangsDeleteOne) Exec(ctx context.Context) error {
	n, err := qldo.qld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quizlangs.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qldo *QuizLangsDeleteOne) ExecX(ctx context.Context) {
	qldo.qld.ExecX(ctx)
}
