// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/vmkevv/duiztapi/ent/predicate"
	"github.com/vmkevv/duiztapi/ent/quiz"
)

// QuizDelete is the builder for deleting a Quiz entity.
type QuizDelete struct {
	config
	hooks    []Hook
	mutation *QuizMutation
}

// Where adds a new predicate to the QuizDelete builder.
func (qd *QuizDelete) Where(ps ...predicate.Quiz) *QuizDelete {
	qd.mutation.predicates = append(qd.mutation.predicates, ps...)
	return qd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qd *QuizDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qd.hooks) == 0 {
		affected, err = qd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuizMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qd.mutation = mutation
			affected, err = qd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qd.hooks) - 1; i >= 0; i-- {
			mut = qd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qd *QuizDelete) ExecX(ctx context.Context) int {
	n, err := qd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qd *QuizDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: quiz.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: quiz.FieldID,
			},
		},
	}
	if ps := qd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, qd.driver, _spec)
}

// QuizDeleteOne is the builder for deleting a single Quiz entity.
type QuizDeleteOne struct {
	qd *QuizDelete
}

// Exec executes the deletion query.
func (qdo *QuizDeleteOne) Exec(ctx context.Context) error {
	n, err := qdo.qd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quiz.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qdo *QuizDeleteOne) ExecX(ctx context.Context) {
	qdo.qd.ExecX(ctx)
}
