// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// AnswerLangs is the predicate function for answerlangs builders.
type AnswerLangs func(*sql.Selector)

// I18n is the predicate function for i18n builders.
type I18n func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// QuestionLangs is the predicate function for questionlangs builders.
type QuestionLangs func(*sql.Selector)

// Quiz is the predicate function for quiz builders.
type Quiz func(*sql.Selector)

// QuizLangs is the predicate function for quizlangs builders.
type QuizLangs func(*sql.Selector)

// Response is the predicate function for response builders.
type Response func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
